// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MIC_mcmc
List MIC_mcmc(Rcpp::List const& data, int const& K, int const& run, int const& thin);
RcppExport SEXP MIC2_MIC_mcmc(SEXP dataSEXP, SEXP KSEXP, SEXP runSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int const& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int const& >::type run(runSEXP);
    Rcpp::traits::input_parameter< int const& >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(MIC_mcmc(data, K, run, thin));
    return rcpp_result_gen;
END_RCPP
}
