# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MIC sampling function in C++
#'
#' \code{MIC_mcmc} performs Gibbs sampling in C++ as an essential part of
#'   \code{\link{MIC}}
#'
#' @param data, R list of 3D array, see \code{\link{MIC}}
#' @param K,    integer as number of clusters
#' @param run,  integer as number of MCMC samples
#' @param thin, integer as thinning every few iterations
#'
MIC_mcmc <- function(data, K, run, thin) {
    .Call('MIC2_MIC_mcmc', PACKAGE = 'MIC2', data, K, run, thin)
}

